services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3344:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - minicurso
    restart: always
      
  db:
    image: postgres:14
    container_name: ${POSTGRES_NAME}-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - minicurso
      
volumes:
  db-data:

networks:
  minicurso:
    external: true
